#ifndef CONFIG_H
#define CONFIG_H

#define WINDOW_WIDTH 1000
#define WINDOW_HEIGHT 1000

#define HIGHSCORES_WIDTH 480

#define PADDLE_SPEED 600
#define PADDLE_WIDTH 100
#define PADDLE_HEIGHT 20
#define PADDLE_Y 950

#define BALL_RADIUS 10
#define BALL_SPEED 350
#define BALL_PACE_ACCELERATION 0.02
#define BALL_ANGLE_CHANGE 10
#define MAX_BALLS_ON_BOARD 50

#define BRICK_WIDTH 60
#define BRICK_HEIGHT 40
#define BRICK_IN_ROWCOL 15

#define BONUS_SIZE 40
#define BONUS_SPEED 200
#define BONUS_CHANCE 0.15
#define BONUS_DELAY 5
#define BONUS_POINTS 10

#define LIVES 3
#define BORDER_WIDTH 50
#define TOP_OFFSET 100

#define TOTAL_STATIC_COLLIDERS 240
#define TOTAL_MOVABLE_COLLIDERS 20

//NIE U¯YWAæ!!!
#define SCREEN_WIDTH 1000
#define SCREEN_HEIGHT 1000
//NIE U¯YWAæ!!!

#endif